name = "ErrorsInVariables"
uuid = "faeb8267-8352-4c3e-81c7-04150084d5bf"
authors = ["jbytecode <mhsatman@gmail.com>"]
version = "0.1.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.4"
